### ISSUE TITLE
Multi-language support.

### ISSUE THREAD

**Issue by arklese1zure** [arklese1zure/medMACROS#1]
If there's any interest in this script, consider researching on how to make all the GUIs support translation.

**Comment by coriolanum** [comment]
Definitely interest

All macros need to be modified to to fit a particular patient. Therefore certain variable need changing. 

The macros can not be pulled to know how many there are that pertain to same patient. 

A list of macros wold facilitate editing text according to patients.

**Comment by arklese1zure** [comment]
OK, so something for showing if previous notes were made for a particular patient?

I could add a new GUI with a search box, and update a listbox based on the user's query. It also could be ordered by name, date or ID.

I'll also get around to converting all text bits to variables, so translation can be done much easier.

Edit: Whoops, didn't mean to close.

**Comment by coriolanum** [comment]
That would work!

**Comment by arklese1zure** [comment]
I made all the GUIs and menus fully translatable, and threw in the english translation for good measure.

I'm currently working on the medical record module.

I think I can close this issue for now.

**Comment by arklese1zure** [comment]
I made all the GUIs and menus fully translatable, and threw in the english translation for good measure.

I'm currently working on the medical record module.

I think I can close this issue for now.
